import mongoose, { Document, Schema, Types } from 'mongoose';

export interface IPlacementReport extends Document {
    _id: Types.ObjectId;
    reportTitle: string;
    batch: string;
    department: string;
    reportType: string;
    minScore: number;
    maxScore: number;
    format: string;
    description: string;
    status: string;
    generatedBy: string;
    createdAt: Date;
    updatedAt: Date;
}

const placementReportSchema = new Schema<IPlacementReport>(
    {
        reportTitle: {
            type: String,
            required: [true, 'Report title is required'],
            trim: true,
            maxlength: [200, 'Report title cannot exceed 200 characters'],
        },
        batch: {
            type: String,
            required: [true, 'Batch is required'],
            trim: true,
        },
        department: {
            type: String,
            required: [true, 'Department is required'],
            enum: ['CSE', 'ECE', 'EEE', 'MECH', 'CIVIL', 'IT', 'ALL'],
        },
        reportType: {
            type: String,
            required: [true, 'Report type is required'],
            enum: ['Batch', 'Department', 'Overall', 'Custom'],
        },
        minScore: {
            type: Number,
            required: [true, 'Minimum score is required'],
            min: [0, 'Minimum score cannot be less than 0'],
            max: [100, 'Minimum score cannot exceed 100'],
        },
        maxScore: {
            type: Number,
            required: [true, 'Maximum score is required'],
            min: [0, 'Maximum score cannot be less than 0'],
            max: [100, 'Maximum score cannot exceed 100'],
        },
        format: {
            type: String,
            required: [true, 'Format is required'],
            enum: ['PDF', 'Excel', 'CSV'],
        },
        description: {
            type: String,
            trim: true,
            default: '',
        },
        status: {
            type: String,
            required: [true, 'Status is required'],
            enum: ['Pending', 'Generated', 'Failed'],
            default: 'Pending',
        },
        generatedBy: {
            type: String,
            required: [true, 'Generated by is required'],
            trim: true,
        },
    },
    {
        timestamps: true,
        toJSON: { virtuals: true },
        toObject: { virtuals: true },
    }
);

placementReportSchema.index({ reportTitle: 1 });
placementReportSchema.index({ department: 1, batch: 1 });
placementReportSchema.index({ status: 1 });

export const PlacementReport = mongoose.model<IPlacementReport>('PlacementReport', placementReportSchema);
